name: 3xui_subscription_manager

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 3xui-subscription-manager-app
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    volumes:
      - ./data:/app/data
    networks:
      - web

  caddy:
    image: caddy:2.10.0
    container_name: 3xui-subscription-manager-caddy
    restart: unless-stopped
    depends_on:
      - app
    environment:
      DOMAIN: ${DOMAIN}
    ports:
      - "3000:3000"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
